language: php

matrix:
  include:
    - php: 5.6
    - php: 7.0
    - php: 7.1
      env:
        - CS_CHECK=true
    - php: 7.2
    - php: 7.3

before_install:
  - composer install --no-interaction

script:
  - ./vendor/bin/phpunit
  - if [[ $CS_CHECK == 'true' ]]; then ./vendor/bin/phpcs ; fi

notifications:
  email: false
